### ISSUE TITLE
Image display error on mobile

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/pannellum#1]
I installed the module and it works great when testing on desktop.  I viewed the page on my iPad and iPhone and got this error.  It seems strange because I've never had to resize a 360 image before.
![image](https://user-images.githubusercontent.com/41843284/62431225-7eabb080-b6f3-11e9-9648-5b033ecedb17.png)

**Comment by keiserjb** [comment]
I reduced the image to 4096px wide in Photoshop and it works just fine.  If anyone else encounters the problem that solves it.

**Comment by laryn** [comment]
I'm curious if the "maximum size" field settings could automatically reduce images to 4096px and still function as expected.

![Screen Shot 2019-08-13 at 11 17 46 AM](https://user-images.githubusercontent.com/871421/62958282-ff397380-bdbb-11e9-8293-4177fdefe02c.jpg)

For now I'm going to [move this into the Wiki ](https://github.com/backdrop-contrib/pannellum/wiki) so it doesn't get lost for future people looking for help on this.

**Comment by keiserjb** [comment]
That works too.
    On Tuesday, August 13, 2019, 12:22:39 PM EDT, Laryn - CEDC.org <notifications@github.com> wrote:  
 
 
I'm curious if the "maximum size" field settings could automatically reduce images to 4096px and still function as expected.



For now I'm going to move this into the Wiki  so it doesn't get lost for future people looking for help on this.
